scripts/README

Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>

scripts: fix typos

---

README

Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>

README: fix typos

---

recipes-core/rauc/rauc-target.inc

added RAUC_KEYRING_FILE variable to handle custom certificate file name instead of ca.cert.pem

added RAUC_KEYRING_FILE variable 

---

recipes-core/rauc/nativesdk-rauc_0.1.1.bb
recipes-core/rauc/nativesdk-rauc_0.2.bb
recipes-core/rauc/rauc-0.1.1.inc
recipes-core/rauc/rauc-0.2.inc
recipes-core/rauc/rauc-native_0.2.bb
recipes-core/rauc/rauc_0.2.bb

The new Release of RAUC just came out, so we should enable meta-rauc users to be up to date ;)

rauc: update to v0.2

---

classes/bundle.bbclass

Signed-off-by: Eugen Wiens <eugen.wiens@jumo.net>
Signed-off-by: Eugen Wiens <wiens.eugens@gmail.com>

make the BUNDLE_NAME and the dependent variables overridable

---

classes/bundle.bbclass

This adds two patches that fix / improve the varflag handling in the bundle class

Further fixes for bundle class varflag handling

---

recipes-core/rauc/rauc-target.inc

rauc-target.in: fix typo in warning message

---

conf/layer.conf

conf: layer: add 'thud' to LAYERSERIES_COMPAT

---

conf/layer.conf

conf: layer: add 'warrior' to LAYERSERIES_COMPAT

---

recipes-devtools/python-aiohttp/python3-aiohttp_3.3.2.bb
recipes-devtools/python-aiohttp/python3-async-timeout_3.0.1.bb
recipes-devtools/python-aiohttp/python3-idna-ssl_1.0.1.bb
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

This fixes support with recent hawkBit versions, increases download
speed and updates to more recent aiohttp, etc.

Update rauc-hawkbit and its dependencies

---

recipes-core/rauc/nativesdk-rauc_1.0.bb
recipes-core/rauc/nativesdk-rauc_1.1.bb
recipes-core/rauc/rauc-1.0.inc
recipes-core/rauc/rauc-1.1.inc
recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-native_1.1.bb
recipes-core/rauc/rauc_1.1.bb

Signed-off-by: Enrico Joerns <ejo@pengutronix.de>

rauc: update to v1.1

---

recipes-support/zstd/zstd_git.bb

Signed-off-by: Søren Andersen <san@skov.dk>

zstd: Enable build of the nativesdk package

---

recipes-support/zstd/zstd_git.bb

Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>

zstd: bump version to v1.4.0

---

.circleci/config.yml
recipes-casync/casync/casync_git.bb

* update to latest master (no release yet)
* add nativesdk build

Update of casync package

---

conf/layer.conf

conf: layer: add 'zeus' to LAYERSERIES_COMPAT

---

classes/bundle.bbclass

This small series:
* fixes variable names in python code
* adds variable documentation varflags
* adds note printouts for adding artifacts to bundle dir
* removed old-style bundle layout warning

Minor fixes, cleanup and documentation for bundle.bbclass

---

classes/bundle.bbclass

allows using rauc/rauc#328 from meta-rauc
Signed-off-by: Manuel Bessler <manuel.bessler@gmail.com>

allow custom extension in place of .raucb

---

recipes-core/rauc/files/rauc-mark-good.service

cherry picked commit from master (see #117)

Backport: rauc-mark-good: Set service to oneshot

---

conf/layer.conf

conf: layer: add 'dunfell' to LAYERSERIES_COMPAT

---

recipes-core/rauc/nativesdk-rauc_1.2.bb
recipes-core/rauc/nativesdk-rauc_1.3.bb
recipes-core/rauc/rauc-1.3.inc
recipes-core/rauc/rauc-native_1.3.bb
recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc
recipes-core/rauc/rauc_1.3.bb

rauc: update to v1.3

---

recipes-core/rauc/nativesdk-rauc_1.3.bb
recipes-core/rauc/nativesdk-rauc_1.4.bb
recipes-core/rauc/rauc-1.4.inc
recipes-core/rauc/rauc-native_1.4.bb
recipes-core/rauc/rauc_1.4.bb

Signed-off-by: Christian Happ <christian.happ@jumo.net>

rauc: update to v1.4

---

recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

Update rauc-hawkbit to latest release 0.2.0.

rauc-hawkbit: Update to latest release 0.2.0

---

README.rst

README.rst: add license and CI builder badge

---

conf/layer.conf

Remove 'dunfell' that will not be tested with current state.

conf: layer: add 'hardknott' to LAYERSERIES_COMPAT

---

.github/workflows/meta-rauc.yml
README.rst
conf/layer.conf
recipes-bsp/dt-utils/dt-utils.inc
recipes-casync/casync/casync_git.bb
recipes-core/bundles/core-bundle-minimal.bb
recipes-core/busybox/busybox_rauc.inc
recipes-core/packagegroups/packagegroup-base_rauc.inc
recipes-core/rauc/files/system.conf
recipes-core/rauc/rauc-native.inc
recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc
recipes-devtools/python-gbulb/python3-gbulb_0.6.1.bb
recipes-kernel/linux/linux-yocto_rauc.inc
recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb
scripts/README

Signed-off-by: Markus Volk <f_l_k@t-online.de>
I can't promise I haven't missed anything, but hopefully there shouldn't be any false positives

convert to new override syntax

---

recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater.inc
recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.0.bb
recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb

Now that v1.0 of rauc-hawkbit-updater was release, this updates the recipes accordingly.

Update rauc-hawkbit-updater recipe(s) for v1.0

---

recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.1.bb

Signed-off-by: Eino Juhani Oltedal <ejo@datarespons.no>

rauc-hawkbit-updater: update to v1.1

---

recipes-core/rauc/nativesdk-rauc_1.5.1.bb
recipes-core/rauc/nativesdk-rauc_1.6.bb
recipes-core/rauc/rauc-1.6.inc
recipes-core/rauc/rauc-native_1.6.bb
recipes-core/rauc/rauc_1.6.bb

rauc: update to 1.6

---

classes/bundle.bbclass

This is inspired by what the bitbake fetcher code does and allows to copy directories, files in directories by preserving the full paths,
etc.

classes: bundle: rework fetcher logic to handle dirs / subdirs etc.

---

conf/layer.conf

Remove 'honister' that will will be maintained in its own branch.
Signed-off-by: Matthias Klein <matthias@extraklein.de>

conf: layer: add 'kirkstone' to LAYERSERIES_COMPAT

---

recipes-bsp/dt-utils/dt-utils.inc
recipes-casync/casync/casync_git.bb
recipes-core/rauc/rauc.inc
recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater.inc
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

Signed-off-by: Matthias Klein <matthias@extraklein.de>

recipes: Update LICENSE variable to use SPDX license identifiers

---

classes/bundle.bbclass

This is #227 backported to kirkstone.

class: bundle: support incremental image property (backport to kirkstone)

---

classes/bundle.bbclass

While 'incremental' was the first name for the new update optimization mode in RAUC, it will be called 'adaptive' in the RAUC 1.8 release where it is first released with functionality behind.

class: bundle: rename 'incremental' image property to 'adaptive'

---

conf/layer.conf

conf: layer: set LAYERSERIES_COMPAT to 'langdale'

---

recipes-core/rauc/nativesdk-rauc_1.8.bb
recipes-core/rauc/rauc-1.8.inc
recipes-core/rauc/rauc-native_1.8.bb
recipes-core/rauc/rauc_1.8.bb

rauc: update to 1.8

---

recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.2.bb

rauc-hawkbit-updater: update to v1.2

---

classes/bundle.bbclass

For most i.MX SoCs, BootROM expects bootloader image to be written into boot media at an offset. While barebox pads the image, so i.MX header starts at that offset, U-Boot doesn't and thus `bundle.bbclass` supported
```
RAUC_SLOT_bootloader[offset] = "32K"
```
To get U-Boot appropriately padded. Now with the i.MX8M Plus and Nano, the tide turns and the BootROM no longer expects an offset for images installed into eMMC boot partitions. It still expects them for SD and eMMC user area. For U-Boot, this means offset can return to the default of 0, but barebox still has a 32K byte preamble, so images are flashable directly to the start of the SD-Card.
To be able to install barebox into an eMMC boot partition on such systems, we will need to shave off these 32K bytes. Allow doing this with:
``` …
```

classes: bundle: allow skipping bytes from image

---

recipes-core/rauc/nativesdk-rauc_1.9.bb
recipes-core/rauc/rauc-1.9.inc
recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-native_1.9.bb
recipes-core/rauc/rauc_1.9.bb

Cherry-pick from master 1c0b05212857cc986d8788e9910bb925966a38c2

rauc: update to 1.9

---

recipes-core/rauc/nativesdk-rauc_1.10.1.bb
recipes-core/rauc/rauc-1.10.1.inc
recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-native_1.10.1.bb
recipes-core/rauc/rauc_1.10.1.bb

Cherry pick the corresponding commit 535bb8191471 from the master branch.

Update RAUC to v1.10.1

---

recipes-core/rauc/nativesdk-rauc_1.11.2.bb
recipes-core/rauc/rauc-1.11.2.inc
recipes-core/rauc/rauc-native_1.11.2.bb
recipes-core/rauc/rauc_1.11.2.bb

(cherry picked from commit f6b3fcd20bc08be8bb41a93feffd94b1626b3c6c)

kirkstone: rauc: update to v1.11.2

---

recipes-core/rauc/nativesdk-rauc_1.11.3.bb
recipes-core/rauc/rauc-1.11.3.inc
recipes-core/rauc/rauc-native_1.11.3.bb
recipes-core/rauc/rauc_1.11.3.bb

(cherry picked from commit 50e1eaf0998357cb9911ec9fadcbbead80d59030)

kirkstone: rauc: update to v1.11.3

---

recipes-core/rauc/rauc-conf.bb

Process ```system.conf``` and the keyring file in the same way.

rauc-conf: Harmonize Installation

---

conf/layer.conf

Be compatible with the upcoming release.

layer.conf: add 'walnascar' to LAYERSERIES_COMPAT

---

recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_1.4.bb
recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb

See https://github.com/rauc/rauc-hawkbit-updater/releases/tag/v1.4

rauc-hawkbit-updater: update to v1.4
