rauc/meta-rauc

classes/bundle.bbclass
recipes-core/rauc/rauc.inc

This patchset fixes building a bundle with current oe-core/Yocto master branches: mostly related to missing/wrong dependencies likely triggered by recent upstream changes that enable recipe specific sysroots.

Fixes for master

---

classes/bundle.bbclass

This is a better estimate then unconditionally setting default to ext4.
Also make it a weak default to ease overwriting it from custom layers.

classes: bundle: let RAUC_IMAGE_FSTYPE default to IMAGE_FSTYPES[0]

---

classes/bundle.bbclass

This will expand the [file] varflag given for a RAUC_SLOT_ and thus
allows using variables in them, such as
RAUC_SLOT_rootfs = "my-${MACHINE}-rootfs.ext4"

bundle.bbclass: allow variables in RAUC_SLOT_ varflag [file]

---

classes/bundle.bbclass

Use weak default assignment when setting RAUC_{KEY,CERT}_FILE to allow
other layers to set default values for key files that can be overridden
in e.g. local.conf when doing release builds.

classes: bundle: use weak defaults assignment for key files

---

recipes-core/rauc/rauc-native_git.bb

switching machines result in
ERROR: rauc-native-0+gitAUTOINC+3867722b8d-r9 do_deploy: The recipe
rauc-native is trying to install files into a shared area when those
files already exist. Those files and their manifest location are:
build/deploy/tools/rauc-0+gitAUTOINC+3867722b8d
Matched in b'manifest-MACHINE1-rauc-native.deploy'
build/deploy/tools/rauc
Matched in b'manifest-MACHINE2-rauc-native.deploy'
Please verify which recipe should provide the above files.
Using DEPLOY_DIR_TOOLS in do_deploy fixes this.
Signed-off-by: Jan Remmet <j.remmet@phytec.de>

rauc-native: use DEPLOY_DIR_TOOLS

---

classes/bundle.bbclass

Depending on `do_image_complete` task is valid for images but
inappropriate for kernel and bootloader which do not have such a task.
This changes the dependency auto-generation in order to honor the image
`type` varflag provided and depend on the `do_deploy` task for kernel
and bootloader.
This fixes #14

classes/bundle: depend on do_deploy task for kernel and bootloader

---

classes/bundle.bbclass

This will automatically clean up previously build bundle artifacts and
remain only the last one, such as it is done for all other images, etc.
This also moves the created bundles from `bundle/` subfolder to the
default image folder. Having a separate `bundle/` folder will not be
required anymore due to the reduced amount of bundles remaining.

classes/bundle: use deploy mechanism to be properly handled by sstate

---

recipes-core/bundles/core-bundle-minimal.bb

This provides both an initial guess for creating your own while allowing
to be a reference for simple automated tests.
Signed-off-by: Enrico Joerns <ejo@pengutronix.de>

add basic example bundle recipe based on core-image-minimal

---

classes/bundle.bbclass

If the check is performed by `python __anonymous()` function, the test
will always be executed right after parsing the recipe.
The result of this is that when not having `RAUC_KEY_FILE`/`RAUC_CERT_FILE`
set, every bitbake invocation will fail, no matter which recipe we gonna
build.
A this is a very bad behavior, we move the check to where it is really
needed: At the beginning of the `do_bundle()` task, right before invoking
RAUC to actually build the bundle.
This way we will abort with a helpful message during do_bundle() task
(when building a RAUC bundle from an non-prepared environment), while
still being able to build all other non-RAUC-related packages without
errors.
Signed-off-by: Enrico Joerns <ejo@pengutronix.de>

classes: bundle: do not check for RAUC_KEY_FILE during parsing

---

README
recipes-devtools/python-aiohttp/python3-aiohttp_2.0.7.bb
recipes-devtools/python-aiohttp/python3-async-timeout_1.4.0.bb
recipes-devtools/python-gbulb/python3-gbulb_0.5.3.bb
recipes-devtools/python/python3-multidict_3.2.0.bb
recipes-devtools/python/python3-yarl_0.11.0.bb
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

This adds recipes for building the (just published) [rauc-hawkbit](https://github.com/rauc/rauc-hawkbit) client.
This is an initial version of the recipes, neither heavily tested nor equipped with any service startup infrastructure. Feel free to test it, provide feedback and improve it.
In order to build it, you also need to enable meta-openembedded/meta-python and meta-openembedded/meta-oe in you bblayers.conf.

add support for RAUC hawkBit client

---

conf/layer.conf

This will error with a helpful message if one of the mandatory layers
(oe-core, meta-oe, meta-pythonA) does not exist instead of failing, for
examples, for a missing class or recipe.

conf/layer.conf: specify LAYERDEPENDS for rauc layer

---

classes/bundle.bbclass

I assume that `file` is not intended to be an image (rootfs)?
If that assumptions is correct, the provided patch should be applied.
Signed-off-by: Leif Middelschulte <leif.middelschulte@gmail.com>

depend on do_deploy for 'file'-SLOTS.

---

classes/bundle.bbclass

Being more verbose in the output might ease analyzing possible issues in
the Yocto log files.

classes: bundle: run rauc with debug output enabled

---

classes/bundle.bbclass

in the case if the image type is not set, the behavior of the dependency can be wrong. Add fatal if the type is not set to prevent unexpected behavior.
Signed-off-by: Eugen Wiens <eugen.wiens@jumo.net>

add check if imgtype is set

---

classes/bundle.bbclass

added selection of the image name with the slotflag 'file'. If the slotflag 'file' is not set, the default image name 'barebox.img' is used.
Signed-off-by: Eugen Wiens <eugen.wiens@jumo.net>

added support for custom barebox image name

---

classes/bundle.bbclass

If you want to create bundles for variants you need image names like
"kernel.variant,1". This doesn't work with VarFlags. Allow to overwrite
the default image name with the name flag-
Signed-off-by: Jan Remmet <j.remmet@phytec.de>

classes: bundle: overwrite default slotname

---

recipes-core/rauc/rauc-native_0.2.bb

Applying fix from 7f5c3e024747ec32f5b61c8aea8fd5fc4da152ed to rauc_native_0.2
also.
Signed-off-by: Kasper Revsbech <krev@triax.com>

rauc-native_0.2: Use DEPLOY_DIR_TOOLS

---

recipes-core/rauc/rauc-native_0.3.bb

Applying fix from 7f5c3e024747ec32f5b61c8aea8fd5fc4da152ed to rauc_native_0.3
also
Signed-off-by: Kasper Revsbech <krev@triax.com>

rauc-native_0.3: Use DEPLOY_DIR_TOOLS

---

README
recipes-casync/casync/casync_git.bb
recipes-support/zstd/zstd_git.bb

This adds basic OE integration for casync, zstd compression lib and adds the RAUC casync support patches as posted [here](https://github.com/rauc/rauc/pull/217).

Add support for building RAUC with casync support

---

recipes-core/rauc/rauc-target.inc

On targets where we do not have mtd storage, there really is no need to
have mtd-utils installed.
This should be added by the respective BSP layer instead.

rauc: rauc-target.inc: do not put mtd-utils in RRECOMMENDS by default

---

recipes-bsp/dt-utils/dt-utils/src-fix-compilation-for-glibc-version-2.27.9000-36.f.patch
recipes-bsp/dt-utils/dt-utils_2017.03.0.bb
recipes-bsp/dt-utils/dt-utils_2018.05.0.bb

This also adds a patch for fixing compilation with newer glibc versions.

dt-utils: update to 2018.05.0

---

recipes-core/rauc/files/rauc-mark-good.init
recipes-core/rauc/rauc-target.inc

When using RAUC on ancient systems without systemd one will also need to
run the rauc-mark-good service after successful start of the system.
This adds basic support for a simple rauc-mark-good initv service in
package rauc-mark-good.

rauc: add rauc-mark-good support for SysVinit

---

classes/bundle.bbclass

S = ${WORKDIR}/bundle can lead to errors like that:
```
WARNING: dummy-bundle-1.0-r0 do_populate_lic: Could not copy license file .../COPYING: [Errno 2] No such file or directory: '.../dummy-bundle/1.0-r0/bundle/COPYING'
ERROR: dummy-bundle-1.0-r0 do_populate_lic: QA Issue: dummy-bundle: LIC_FILES_CHKSUM points to an invalid file: .../dummy-bundle/1.0-r0/bundle/COPYING [license-checksum]
```
Since bitbake uses S variable as a path to source directory it seems correct to use separate dir for bundle contents.

do not use {S}ource dir as bundle contents dir

---

recipes-core/rauc/nativesdk-rauc_1.0.bb
recipes-core/rauc/rauc-1.0.inc
recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-native_1.0.bb
recipes-core/rauc/rauc_1.0.bb

This adds RAUC 1.0 to the existing set of recipes.
It is highly recommended to switch to the 1.0 release that is fully
compatible with 0.4 but fixes several potential issues.
However, for those that need to stick to an older version for whatever
reason, the old recipes are kept.
You can set an explicit version as follows somewhere in your global
configuration:
PREFERRED_VERSION_rauc = "0.4"

[thud] rauc: add RAUC 1.0 recipe

---

classes/bundle.bbclass

Allow to use a non-autogenerated image name.
Signed-off-by: Gero Schumacher <gero.schumacher@peiker-cee.de>

classes: bundle: support [file] varflag for type 'image'

---

recipes-core/rauc/nativesdk-rauc_1.1.bb
recipes-core/rauc/rauc-1.1.inc
recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-native_1.1.bb
recipes-core/rauc/rauc_1.1.bb

This adds RAUC 1.1 to the existing set of recipes.
It is highly recommended to switch to the 1.1 release that is fully
compatible with 1.0 but fixes several potential issues.
However, for those that need to stick to an older version for whatever
reason, the old recipes are kept.
You can set an explicit version as follows somewhere in your global
configuration:
PREFERRED_VERSION_rauc = "1.0"
Signed-off-by: Enrico Joerns <ejo@pengutronix.de>

[backport] rauc: add RAUC 1.1 recipe

---

.circleci/bblayers.conf.sample
.circleci/config.yml
.circleci/local.conf.sample

circleci allows us to cache results which enables saving and restoring sstate-cache to speed up builds.
This, combined with using sstate.yoctoproject.org reduces the build time of meta-rauc components to a few minutes and makes it appropriate for CI testing.

Add CI testing via circleci

---

recipes-devtools/python-gbulb/python3-gbulb_0.6.1.bb

@ejoerns: Here we go.
rauc-demo now fails for another, but unrelated reason on warrior.

python3-gbulb: Update to 0.6.1 for Python 3.7 support.

---

.circleci/config.yml

Docker hub crops/yocto removed ubuntu-18.10-builder tag which causes
circleci workflow to fail with:
| Error response from daemon: manifest for crops/yocto:ubuntu-18.10-builder not found
Replace this by the more recent and available tag ubuntu-19.04-builder.

.circleci: config.yml: replace removed crops/yocto image 18.10 by 19.04

---

classes/bundle.bbclass

We create a bundle and thus do not require generating any of the default
packages. Thus set
PACKAGES = ""
We also do not require default dependencies such as C compiler for a
bundle, thus also set
INHIBIT_DEFAULT_DEPS = "1"

classes: bundle: do not generate default packages and deps

---

recipes-core/rauc/rauc-target.inc

The bb.utils.contains() mechanism won't work if the bootloader isn't
named exactly barebox or u-boot. A quick google serch shows that there
are a few u-boot variants: u-boot-imx, u-boot-fslc, u-boot-seco,
u-boot-digilent, ... We should take this into account and make a
substring search.
Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>

rauc: rauc-target.inc: improve RDPENDS handling

---

recipes-core/rauc/rauc-target.inc

Implementing guessing of the valid boot tools in inline python
oneliners turned out to be both error-prone and hard to read.
This fixes the current handling which fails if
PREFERRED_PROVIDER_virtual/bootloader is not set and additionally
extends it by also covering 'grub' as possible bootloader.

rauc: more generic and stable boot tool guessing

---

recipes-core/rauc/nativesdk-rauc_1.1.bb
recipes-core/rauc/nativesdk-rauc_1.2.bb
recipes-core/rauc/rauc-1.1.inc
recipes-core/rauc/rauc-1.2.inc
recipes-core/rauc/rauc-native_1.2.bb
recipes-core/rauc/rauc.inc
recipes-core/rauc/rauc_1.2.bb

RAUC 1.2 requires dbus pkg-config files in case of service being
enabled.

rauc: update to v1.2

---

classes/bundle.bbclass

These variables can contain PKCS#11 URIs, for which `;` and `&` are
valid characters. Avoid parsing issues by quoting them.

classes: bundle: quote cert and key argument values for bundle creation

---

recipes-bsp/dt-utils/dt-utils.inc

PN may contain common prefixes as -native or nativesdk- and is thus
inappropriate for SRC_URI. Replace by BPN which has these prefixes
removed.
This also fixes QA issue:
>  do_package_qa: QA Issue: dt-utils: SRC_URI uses PN not BPN [src-uri-bad]

dt-utils: replace PN by BPN in SRC_URI

---

classes/bundle.bbclass

This can be useful if the name produced by the build system doesn't have the suffix expected by rauc or if there is information in the name that should not be published.

classes: bundle: support overriding file names in the bundle

---

recipes-core/rauc/rauc-1.2.inc

Fixes:
```
$ ./auto-upgrade-helper/upgradehelper.py rauc
INFO: Skip package rauc (status = UNKNOWN_BROKEN, current version = 1.2, next version = N/A)
```
With this commit:
```
INFO: Skip package rauc (status = MATCH, current version = 1.2, next version = 1.2)
```
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

rauc: fix upstream version check

---

classes/bundle.bbclass

While it will work as is, it probably shouldn't land until https://github.com/rauc/rauc/pull/537 lands.

Add BUNDLE_ARGS variable.

---

classes/bundle.bbclass

It doesn't make much sense to define global or per-slot hooks without
providing a file that actually implements those, so at least warn
about that - maybe bb.warn can be promoted to an error later.
It might make sense to move this sanity check to the "rauc bundle"
command, so one would also catch the cases where the bundles are not
created via Yocto. Also, a run-time warning when (or before)
installing such a malformed bundle would be nice. But that's all a lot
more code change than this.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>

bundle.bbclass: check that a hook file is provided

---

recipes-core/rauc/files/rauc-mark-good.service

Setting rauc-mark-good to oneshot was also discussed in issue #86
I faced a different problem with the same solution:
Because the rauc-mark-good.service has Type=simple the boot process
continues after the service was started NOT after rauc mark good was finished.
It is not possible to start a service that depends on rauc-mark-good.service because the execution of the service lasts about 1,5s in our case (write to EEPROM).
With this patch it is possible to order a service just after `rauc-mark-good` is finished.

rauc-mark-good: Set service to oneshot

---

conf/layer.conf

Since ce1fe455f8cc83484eea4b4b515a3104d1aac02a ("python3: remove outdated packages") meta-rauc has a .bbappend file for the recipe python3-yarl (version 1.3.0).
This now moves meta-python from a recommendation to an actual dependency as otherwise building the layer will fail with:
```
ERROR: No recipes available for:
/path/to/bsp/meta-rauc/recipes-devtools/python/python3-yarl_1.3.0.bbappend
```

conf: layer.conf: python3-yarl bbappend requires meta-python

---

recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb

rauc-hawkbit-updater is a simple command line tool (or daemon) written
in C (glib). It is a port of the RAUC hawkBit client written in Python.
The daemon operates as an interface between the RAUC D-Bus API and the
hawkBit DDI API.
Please apply to sumo and later.

Add recipe for rauc-hawkbit-updater

---

recipes-core/rauc/files/rauc-mark-good.service

systemd has a dedicated, special target called `boot-complete.target` that indicates,
that a boot-up is considered successful.
Citing the documentation[0]:
> This target is intended as generic synchronization point for services that shall determine or act on whether the boot process completed successfully. [...]
[0] https://www.freedesktop.org/software/systemd/man/systemd.special.html#boot-complete.target

rauc-mark-good.service: leverage systemd's sync target

---

classes/bundle.bbclass

Allow extra arguments to be passed to `rauc bundle` command.
Signed-off-by: Louis des Landes <louis.deslandes@fleet.space>
(backported from commit d0211ddc0f4283da95bc598249e529fc0297ddac
github.com/rauc/meta-rauc master)
Signed-off-by: Maik Otto <m.otto@phytec.de>

[warrior+] BACKPORT: Add BUNDLE_ARGS variable.

---

recipes-core/rauc/rauc-native.inc
recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc

Currently rauc-native RRECOMMENDS squashfs-tools, but it should really
be squashfs-tools-native instead. Normally this distinction is handled
by some magic in native.bbclass, which munges all package relationships
to hack -native onto the end of the names:
https://github.com/openembedded/openembedded-core/blob/master/meta/classes/native.bbclass#L141
but that code only runs if you use BBCLASSEXTEND = "native". If the
recipe explicitly inherits native, as rauc-native does, the renaming
does not happen. Thus the recipe needs to spell out its -native
dependency explicitly.

rauc: fix RRECOMMENDS for rauc-native -> squashfs-tools-native

---

classes/bundle.bbclass

Add an option to build a casync bundle alongside the regular bundle.
This requires setting an appropriate keyring. Activate the generation of
casync bundles by setting RAUC_CASYNC_BUNDLE to "1".
Signed-off-by: Martin Schwan <m.schwan@phytec.de>

classes: bundle: Add option to build casync bundle

---

recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb

Add a system user "rauc-hawkbit" that is used by the systemd service of rauc-hawkbit-updater.
This fixes https://github.com/rauc/rauc-hawkbit-updater/issues/44.

rauc-hawkbit-updater: Add user rauc-hawkbit

---

classes/bundle.bbclass

If ever depending on a bundle in another recipe (i.e. for embedding a
bundle in another image), you currently get missing manifest issues due
to the existing packaging tasks that do not execute and thus do not
generate any manifest:
| ERROR: test-image-1.0-r0 do_rootfs: No manifest generated from: core-bundle-minimal in [..]/core-bundle-minimal.bb
This applies the same fix as poky commit
49f7c2cd87adafb2130addedf69d5f67dc1f2a22 by simply deleting the
respective tasks.
Signed-off-by: Matthew Campbell <mcampbell@izotope.com>

bundle: Remove the do_package_write_* tasks

---

classes/bundle.bbclass

When renaming files in a bundle it can be useful to allow for expansion of bitbake macros in the new file name.
Fixes #133

classes: bundle: Expand bb macros when overriding file name

---

recipes-support/rauc-hawkbit/files/rauc-hawkbit.service
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

This adds a systemd service for the rauc-hawkbit client to easily start and stop it. ~By default, this service is disabled, as I think not everyone wants to use the rauc-hawkbit client on their system.~
Additionally, for an easier configuration of the client the config file is being linked to /etc.
These changes should be applied to sumo and later.

rauc-hawkbit: Add systemd service

---

classes/bundle.bbclass

Replace "CONVERTS_ARGS" with correct "CONVERT_ARGS" in the description
of the bundle.bbclass.
Signed-off-by: Martin Schwan <m.schwan@phytec.de>

classes: bundle: Fix typo "CONVERTS_ARGS"

---

classes/bundle.bbclass

This file is expected to be provided by the fetcher normally, thus we
should add the required SRC_URI entry in the example.
Fixes #84

classes: bundle: add hook to SRC_URI in example

---

recipes-core/rauc/rauc.inc

D-Bus is required to communicate with the RAUC service.
Especially on non-systemd distros like poky it could be the case that
there is no D-Bus at all without this explicit runtime dependency.

rauc: rauc-service has a runtime dependency on dbus

---

recipes-core/busybox/busybox_%.bbappend
recipes-core/busybox/files/0001-mount-support-the-sizelimit-and-offset-option-for-lo.patch

Without this patch, busybox mount cannot be used for current RAUC with
kernel > 5.4.
Fixes: rauc/rauc#553

busybox: add patch to support 'sizelimit' and 'offset' option for lo

---

conf/layer.conf

Remove 'zeus' that will not be tested with current state.

conf: layer: add 'gatesgarth' to LAYERSERIES_COMPAT

---

classes/bundle.bbclass

This fixes some long-existing issues with artifact fetching and error handling of bundle.bbclass.
One of them was that when modifying artifact names, an artifact from a previous build could still be in the bundle creation folder and thus in the bundle unintentionally.

bundle.bbclass: fixes for collecting artifacts

---

classes/bundle.bbclass

We already have a look at `WORKDIR` when searching for
`RAUC_BUNDLE_EXTRA_FILES` artifacts.
Doing the same for images too will potential allow generating required
artifacts right from the bundle recipe run and use them as images to be
copied to `BUNDLE_DIR`.

classes: bundle: add WORKDIR also to regular image search space

---

recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc

This allows to enable atomic updates of bootloaders on primary GPT
partition. Add to defaults for the target package.
See https://rauc.readthedocs.io/en/latest/advanced.html#update-boot-partition-in-gpt

rauc: add 'gpt' to PACKAGECONFIG

---

classes/bundle.bbclass

Option to set an offset in the slot parameter for the bootloader image. New bootloader image
with the set offset is created via "dd" command.
resolves rauc/rauc#596

bundle: Add slot parameter for bootloader offset

---

classes/bundle.bbclass

According to Wiki Yoctoproject FuncFailed is deprecated with 3.0, see
https://wiki.yoctoproject.org/wiki/FutureMigrationGuide section "Bitbake
changes".
Fixes https://github.com/rauc/meta-rauc/issues/162
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

classes: bundle: use fatal() instead of FuncFailed

---

classes/bundle.bbclass
recipes-core/rauc/files/system.conf
recipes-core/rauc/nativesdk-rauc_1.4.bb
recipes-core/rauc/nativesdk-rauc_1.5.bb
recipes-core/rauc/rauc-1.5.inc
recipes-core/rauc/rauc-native_1.5.bb
recipes-core/rauc/rauc_1.5.bb

Important: This fixes [CVE-2020-25860](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25860)

rauc: update to v1.5

---

recipes-core/rauc/nativesdk-rauc_1.5.1.bb
recipes-core/rauc/nativesdk-rauc_1.5.bb
recipes-core/rauc/rauc-1.5.1.inc
recipes-core/rauc/rauc-native_1.5.1.bb
recipes-core/rauc/rauc_1.5.1.bb

Update for 1.5 with casync bundle manifest generation fix and
compatibility fixes for older glib versions, kernel headers, etc.
Drop deprecated md5sum hash.

rauc: update to v1.5.1

---

recipes-core/rauc/rauc-native.inc

avoid this qa warning:
QA Issue: rauc-native: native/nativesdk class is not inherited last,
this can result in unexpected behaviour.  [native-last]

rauc-native.inc: reorder inherit to silence recently added qa check

---

classes/bundle.bbclass

Do not let 'bundle' task be explicitly ordered before do_build as this
will add a dependency
"update-bundle-dev.do_rm_work" -> "update-bundle-dev.do_bundle"
which will always retrigger do_bundle task when rm_work is invoked.
The explanation for this is that do_bundle is not an sstate-enabled task.
Thus while rm_work will erase the task output it will also triggers its
rebuild then.
Triggering of do_bundle is ensured by do_deploy task that depends on
do_bundle and is triggered by do_build.

bundle.bbclass: fix task ordering for rm_work

---

classes/bundle.bbclass

Enable the pseudo command for rauc convert by setting the appropriate environment variable. Otherwise casync bundle contents may not have the correct permissions upon extraction.
Fixes https://github.com/rauc/rauc/issues/598

classes: bundle: Enable pseudo for rauc convert

---

classes/bundle.bbclass

This basically does the same as poky commits do for image.bbclass:
* 7fb3c6a40adb0f6c3032b0a5628c8a56b0e7bd4a
"image/packagegroup/populate_sdk: Drop do_populate_sysroot task properly"
(OE-Core: bd7d0314038a4c1a8e8c9ebdb7194f8e17db3fe)
* 60662a2117373648a0a41b3556e180f7a7350a47
"image/kernelsrc/packagegroups/recipes: Remove uneeded noexec tasks"
(OE-Core 4e6ee37e09c60e83c0dfd844ba9cf8a07507f099)
As we do not execute this task, we do not generate a manifest here etc.
Fully drop them to simplify task dependencies.

classes: bundle: drop some unneded noexec tasks

---

classes/bundle.bbclass

This fixes using RAUC_BUNDLE_EXTRA_DEPENDS resulting in broken
dependencies like recipe:task:task.

Fix RAUC_BUNDLE_EXTRA_DEPENDS

---

classes/bundle.bbclass

In some cases the image to include in RAUC bundle
may be inside a $DEPLOY_DIR_IMAGE subdirectory
and imgname variable will contains it in the path.
The result is a failure at the image copy and the
filename manifest field also contains it.
This change wrap the imgname with a Python PurePath
to keep only the image filename instead of full path.
Signed-off-by: Jarsop <jarsop@outlook.com>

classes: bundle: add support to find imagesource in subdir

---

classes/bundle.bbclass

Let user to customize Casync bundle name using CASYNC_BUNDLE_*NAME set
of variables similarly to BUNDLE_*NAME used for conventional bundles.
New set has similar dependency scheme except that it uses new variable
CASYNC_BUNDLE_BASENAME instead of BUNDLE_BASENAME.
The CASYNC_BUNDLE_BASENAME defaults to "casync-${BUNDLE_BASENAME}" so
this patch makes no changes in bundle names until user would like to
provide custom ones.
Also fix inconsistence in ${B}/casync-bundle.raucb name in do_bundle
and do_deploy tasks.
Signed-off-by: Vitaly Kuzmichev <vkuzmichev@dev.rtsoft.ru>

classes: bundle: Allow to change Casync bundle name

---

classes/bundle.bbclass

This fixes using RAUC_BUNDLE_EXTRA_DEPENDS resulting in broken
dependencies like recipe:task:task.
Signed-off-by: Harald Brinkmann <Harald.Brinkmann@detectomat.com>
(cherry picked from commit edd1e12915dff2c8a11e270aa8a1565666d6b808)

Cherrypick RAUC_BUNDLE_EXTRA_DEPENDS fix to dunfell

---

recipes-core/rauc/files/rauc-mark-good.service

Make the rauc-mark-good.service run only if `bootchooser.active` or `rauc.slot` are set in the kernel command line. During
debugging/development, boot from NFS or non-bootchooser boots might be used. In these cases `rauc status mark-good` will fail.
`RemainAfterExit=yes` allows systemd to start dependencies only after `rauc status mark-good` has succeeded.
While at it, use the official RAUC spelling and remove the trailing empty line.

rauc: rauc-mark-good: improve service unit

---

README.rst

1. deploy casync native binary to tmp/deploy/tools/casync
1. bump casync source revision to 4ad9bcb94bc83ff36cfc65515107ea06a88c2dfc

deploy casync native to tools dir

---

recipes-casync/casync/casync_git.bb
recipes-core/rauc/rauc-git.inc
recipes-support/rauc-hawkbit-updater/rauc-hawkbit-updater_git.bb
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

Update the SRC_URIs to include a branch and to include a protocol for
GitHub. This was performed using the convert script from
openembedded-core.
Signed-off-by: Marcel Hamer <marcel@solidxs.se>

recipes: Update SRC_URI branch and protocols

---

classes/bundle.bbclass

Trust the environment RAUC is executed in when converting bundles. This fixes the following error message:
> initial check_bundle_access failed with: unable to find mounted device for bundle
---
I am keeping this PR as a draft for the moment, until https://github.com/rauc/rauc/pull/770 is merged.

classes: bundle: Trust environment for "rauc convert"

---

recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc

With v1.7 being released and available as recipe, the streaming option
can be enabled for all supported RAUC recipes.
Thus move the option to rauc.inc and enable streaming support in the
default target PACKAGECONFIG.

rauc: move 'streaming' PACKAGECONFIG option to common includes

---

classes/bundle.bbclass

To build bundles with incremental support, we need to define the new property
for relevant images. As RAUC 1.7 already supports (and then ignores) this
property, we can add the support now.

class: bundle: support incremental image property

---

classes/bundle.bbclass

Building a bundle with having 'rm_work' class enabled did not lead to
rm_work tasks being run for recipes that were dependencies of the rootfs
image recipe used.
This was something between annoying and unexpected and the only
workaround so far was to also explicitly build the root file system
recipe used by the bundle which triggered rm_work correctly.
The reason why rm_work is not triggered by bundle builds lies in the
way the bundle class depends on images.
For depending on images we must depend on the 'do_image_complete' task
instead of 'do_build' (like one would for normal packages).
Now, the rm_work class works by injecting its tasks as dependencies of
'do_build'. It adds a high-level 'do_rm_work_all' task that itself
depends (via recrdeptasks) on the actual 'do_rm_work' worker tasks …

classes: bundle: hack in support for rm_work

---

recipes-core/rauc/rauc-git.inc

This has been forgotten in #240.

rauc-git: update recipe version to 1.8

---

classes/bundle.bbclass

Allow for BitBake variable parsing inside the variable flags "offset", "hooks" and "adaptive". To enable this, use d.getVarFlag() instead of the builtin get() method.

classes: bundle: Allow parsing var flags offset, hooks and adaptive

---

README.rst
recipes-core/rauc/rauc-native.inc

Using tmp/deploy/tools for deploying native tools is nowadays used hardly anywhere. It also has some severe drawkbacks since it relies on having matching shared libs in the host system.
Now, with poky having moved to openssl 3.0 and most distros have not, yet, this became unusable for most people, anyway.
They will run into this error:
> tmp/deploy/tools/rauc: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
The recommended way of using native tools in Yocto is to use oe-run-native. Document this in the README instead of the old deploy-way..

rauc-native: do not deploy tool anymore

---

classes/bundle.bbclass

This is the next step towards deprecating the 'plain' format. We start enforcing an explicit decision whether to use old 'plain' or new 'verity' format.
And we guide the user to use 'verity' for new projects.

classes: bundle: warn if RAUC_BUNDLE_FORMAT is not set

---

recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc

The service is only relevant for the target and should thus not be defined in the generic rauc.inc.
This also fixes an actual bug since the dependency
| RDEPENDS:${PN}-service += "dbus"
applies to the target package as it applies to -native and nativesdk- as well. And the latter two are clearly wrong.

rauc: move rauc-service to rauc-target.inc

---

conf/layer.conf

Upstream oe core has updated the release name from langdale to mickledore.
Signed-off-by: Theodore A. Roth <troth@openavr.org>

Update layer compat to mickledore

---

recipes-core/rauc/nativesdk-rauc.inc
recipes-core/rauc/nativesdk-rauc_1.8.bb
recipes-core/rauc/nativesdk-rauc_git.bb

With https://github.com/rauc/meta-rauc/commit/815e9130f9aee5c7e6f5c027a3102bc79ada9082 ("rauc: move rauc-service to rauc-target.inc") the FILES
variable was modified to not collect the dbus- and service-related files
installed by RAUC anymore.
This causes the nativesdk build to fail. Since the service files are
pointless in a nativesdk anyway, we simple remove them with a
do_install:append().
Fixes:
```
ERROR: nativesdk-rauc-1.8-r0 do_package: QA Issue: nativesdk-rauc: Files/directories were installed but not shipped in any package:
/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-pokysdk-linux/lib
/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-pokysdk-linux/usr/share/dbus-1
/usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-pokysdk-linux/usr/share/dbus-1/system.d …
```

Fix nativesdk build

---

recipes-core/rauc/nativesdk-rauc.inc
recipes-core/rauc/rauc-target.inc
recipes-core/rauc/rauc.inc

With v1.9, RAUC switched to using meson. Autotools support is kept only for transition phase and might be removed in v1.10.

rauc: switch to meson

---

recipes-core/rauc/rauc-target.inc

The rauc-service package was overriding the SYSTEMD_PACKAGES variable which resulted in the rauc-mark-good systemd service not receiving it's post install scripts. Now the service should be enabled by default as intended.

Fixed rauc-mark-good systemd service setup.

---

classes-recipe/bundle.bbclass

With `RAUC_META_SECTIONS` there is a similar approach to how bundles are defined that allows to specify RAUC [meta data sections](https://rauc.readthedocs.io/en/latest/reference.html?highligh=meta#manifest) in the manifest.
With `RAUC_MANIFEST_EXTRA_LINES` any (RAUC-parsable) manifest information can be appended to a manifest.

Add Two Ways of Adding Custom Meta-Data Or Settings to The Manifest

---

recipes-core/rauc/rauc.inc

* Fixes using EXTRA_OECONF where EXTRA_OEMESON should be used
* disables building tests (avoids potential build issues)

Fixes for building RAUC with meson

---

classes-recipe/bundle.bbclass

Since oe-core commit openembedded/openembedded-core@26d97acc71379ab6702fa54a23b6542a3f51779c ("image-artifact-names: include ${IMAGE_NAME_SUFFIX} directly in both ${IMAGE_NAME} and ${IMAGE_LINK_NAME}"), now also image symlinks contain the '.rootfs' suffix that images already had.
Adapt to this change by adding ".rootfs" to the default search path for rootfs images (i.e. their symlinks).

classes-recipe: bundle: add ".rootfs" to default image search path

---

recipes-core/bundles/core-bundle-minimal.bb

The 'plain' format should not be used anymore but the 'verity' format still requires explicit selection.
So use the appropriate format for this example.
This will also silence the warning generated for this case:
>  WARNING: core-bundle-minimal-1.0-r0 do_configure: No RAUC_BUNDLE_FORMAT set. This will default to using legacy 'plain' format.
> If you are unsure, set RAUC_BUNDLE_FORMAT = "verity" for new projects.
> Refer to https://rauc.readthedocs.io/en/latest/reference.html#sec-ref-formats for more information about RAUC bundle formats.

bundle: core-bundle-minimal: use verity format

---

README.rst
recipes-core/rauc/files/system.conf

An entry for "system.conf" has already been added via rauc-target.inc.

Remove Redundant Extension of SRC_URI from README.rst and system.conf

---

recipes-core/rauc/rauc.inc

As the `dbusinterfacesdir` variable was not explicitly set and the default was evaluating to `/etc/dbus-1/system.d`, `bitbake` was not able to properly add file `de.pengutronix.rauc.Installer.xml` in `rauc-dev` package.
See also rauc/rauc#1184.

rauc: explictly set dbusinterfacesdir

---

recipes-core/rauc/rauc-target.inc

When the `PACKAGECONFIG` did not include `"service"`, bitbake was failing with
ERROR: rauc-1.10-r0 do_package: Didn't find service unit 'rauc.service', specified in SYSTEMD_SERVICE:rauc-service.
Fixed this by setting the `SYSTEMD_SERVICE` variable only when the corresponding service flag in the `PACKAGECONFIG` variable is also set.
This should fix #279

rauc: register systemd service only if configured

---

conf/layer.conf

Since core layer switch to `nanbield` release series we have to update our `layer.conf` file.
This commit [e81981e](https://git.yoctoproject.org/poky/commit/meta/conf/layer.conf?id=e81981e317f8bece2807e39a05916fdc58f26017) introduce that

feat(layer.conf): switch to nanbield series

---

recipes-bsp/dt-utils/dt-utils_2023.08.0.bb
recipes-bsp/dt-utils/dt-utils_2023.11.0.bb

This release fixes an issue when using barebox-state on systems with a barebox state partition on the eMMC user partition. Without this patch barebox-state searches for the state partition on one of the eMMC boot (hardware) partitions.
Fixes: 6c5faed ("dt-utils: update to 2023.08.0")
(cherry picked from commit 564181f3fd119a37f4dfe04f179b5f6cc7807730)

[mickeldore backport] dt-utils: update to 2023.11.0

---

classes-recipe/bundle.bbclass

Any recipe using the `bundle` bbclass will fail if either:
- `${prefix}` is not equal to `${prefix_native}`, or:
- `${prefix_native}` is not equal to `/usr`, or:
- `${bindir}` is not equal to `${bindir_native}`
This PR corrects this by using `${prefix_native}` and `${STAGING_BINDIR_NATIVE}` where appropriate.

classes-recipe: bundle: use native paths instead of target paths

---

classes/bundle.bbclass

Backport that feature to be able to let RAUC update an eMMC's boot partitions correctly for an i.MX8 based system.

Allow Skipping Bytes from Image

---

classes-recipe/bundle.bbclass

~Python anonymous functions are evaluated before `=` which expand the final variable value. This fix set the `getVarFlags` kwarg `expand` to `True` (default is `False`) to be able to assign varflag with bitbake variable (`${...}`) or python inline syntax (`${@...})`.~
Python anonymous functions are evaluated before the `=` sign and Python tasks do not expand variables. This fix introduces a set of varflags via `RAUC_VARFLAGS_SLOTS` and `RAUC_VARFLAGS_HOOKS` variables.
It sets the `getVarFlags` keyword argument `expand` to the respective list (default is `False`). This allows for assigning varflags using bitbake variables (`${...}`) or Python inline syntax (`${@...}`).

fix: bundle.bbclass: varflags expansion

---

classes-recipe/bundle.bbclass

.rootfs is just the default for IMAGE_NAME_SUFFIX but could be changed by users.
Inherit image-artifact-names class where the variable is defined.
Fixes #299

bundle.bbclass: use IMAGE_NAME_SUFFIX instead of hard-coded '.rootfs'

---

recipes-core/rauc/rauc-conf.bb
recipes-core/rauc/rauc-target.inc

rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration
This allows to build 'rauc' with default TUNE_PKGARCH while only 'rauc-conf' needs to be build for MACHINE_ARCH as it contains MACHINE-specific configuration.
Another point is that the RAUC configuration may not only by MACHINE-specific but may also differ between images (for the same MACHINE).
The rauc target package now `RRECOMMENDS` rauc-conf to pull this in by default.
For providing your own configuration, either bbappend the existing rauc-conf recipe, write a new one that provides 'virtual-rauc-conf' and set `PREFERRED_PROVIDER_virtual-rauc-conf` or just write a custom one and add it to your image's `IMAGE_INSTALL` list (or any packagegroup).
Either way, this requires migration in your rauc recipe(s)!

rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration

---

.github/workflows/meta-rauc.yml

Since meta-openembedded commit ab7c469b ("meta-networking: Express dependency on meta-python"), meta-networking depends on meta-python. Thus add meta-python before adding meta-networking.

.github: workflows: meta-rauc: meta-networking depends on meta-python

---

conf/layer.conf

Since oe-core switched to `scarthgap` release series only (i.e. removed `nanbield` compatiblity), we have to update our `layer.conf` file.

layer.conf: switch to scarthgap series

---

classes-recipe/bundle.bbclass

Similar to #299, when changing the default IMAGE_MACHINE_SUFFIX the bundle build fails (error in do_configure()).
The fix is identical to #300.

bundle.bbclass: use IMAGE_MACHINE_SUFFIX instead of hard-coded '-${MACHINE}'

---

recipes-core/rauc/files/rauc-mark-good.service

Having implicit dependencies enabled would lead to ordering cycles when enabling 'boot assessment', through
systemd-boot-check-no-failures [1], which is a service that forces the multi-user.target to be reached before the boot-complete.target.
The ordering cycle in this case would be:
boot-complete -requires-> systemd-boot-check-no-failures systemd-boot-check-no-failures -after-> multi-user rauc-mark-good -after-> boot-complete
boot-complete -after-> multi-user
multi-user -after-> rauc-mark-good
Which systemd would break by simply not running rauc-mark-good.
The solution is to disable implicit dependencies that would otherwise add an 'After=rauc-mark-good.service' to the multi-user.target via the [Install] section.
Link: https://www.freedesktop.org/software/systemd/man/latest/systemd-boot- …

rauc: rauc-mark-good: disable implicit dependencies

---

classes-recipe/bundle.bbclass
conf/layer.conf
recipes-core/rauc/rauc-conf.bb
recipes-core/rauc/rauc-target.inc
recipes-support/rauc-hawkbit/rauc-hawkbit_git.bb

This adapts to the oe-core rework to enforce a separate directory for unpacking local sources (`UNPACKDIR`) instead of polluting `WORKDIR` directly.
Follows the preliminary guidelines from:
https://lists.openembedded.org/g/openembedded-architecture/message/2007
For this, we need to break compatibility with all releases before `master`.

Follow WORKDIR -> UNPACKDIR transition

---

classes-recipe/bundle.bbclass

* fix hooks example (addressed by #321)
* inherit `nopackages`
* remove duplicate hyphen in bundle compatible
* no need to set deploy cleandirs

bundle.bbclass: Some Cleanups and Fixes

---

classes-recipe/bundle.bbclass

The artifacts created are quite large and keeping multiple of them will consume a notable amount of disk space while the expected speed-up is minimal.
(For the same reasons, the image class does not generate SSTATE artifacts).
Having SSTATE artifacts for bundles enabled can also lead to unexpected/unwanted behavior if a rootfs image recipe was rebuild and the binary output (file system image) changed but did not make it into the final bundle.
This becomes a major problem, e.g. in the context of verified boot.

bundle.bbclass: do not generate SSTATE artifacts

---

README.rst

Support for placing the native rauc tool under the deploy directory was removed a while ago in favor of the better oe-run-native approach (which uses the proper native sysroot, too).
Somehow this misleading comment survived the README update then.
Fixes: 79554c6 ("rauc-native: do not deploy tool anymore")

README.rst: remove left-over reference to tmp/deploy/tools

---

README.rst

In master, with commit 79554c6 ("rauc-native: do not deploy tool anymore") support for running rauc from `DEPLOYDIR` was removed.
Let's keep it in kirkstone to not break existing workflows, but discourage to use it and document the proper `oe-run-native` approach instead.

README.rst: discourage to use rauc-native from DEPLOYDIR

---

README.rst
scripts/README

With d51bab8f (rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration), users need to append rauc-conf instead of rauc when providing their device-specific configuration.
This was not reflected by the docs yet.
Also add an explicit migration note early in the README.rst.

README: rauc-conf needs to be appended now instead of rauc

---

recipes-core/rauc/rauc-git.inc
recipes-core/rauc/rauc-target.inc

With the latest master branch state, RAUC gained support for installing a systemd catalog file.
Add the catalog path to the common `FILES:${PN}-service` for `rauc-target.inc` sine it will not have an impact when using it with a release not containing the catalog file.

rauc-git: update to latest SRCREV

---

recipes-support/curl/curl_%.bbappend
recipes-support/curl/curl_rauc.inc

Without HTTP/2 support, streaming installation is significantly slower.

curl: enable PACKAGECONFIG for HTTP/2 (nghttp2) on the target

---

classes-recipe/bundle.bbclass

variables assigned to `RAUC_META_<section>[varflag]` are not expanded anymore.
This is caused by `getVarFlags` not expanding variables by default, revert to using `getVarFlag` which does expand variables by default.
fix #335
partially revert changes introduced in ffba61f2f79ec03395629d8713a59226b0158d5f

bundle.bbclass: fix variable expansion of RAUC_META_* varflags

---

classes-recipe/bundle.bbclass

The SRC_URI always requires a URI scheme.

bundle.bbclass: fix hook SRC_URI example

---

.github/workflows/build.yml

This is based on @hnez's [forrest runner](https://github.com/hnez/forrest), which provides ephemeral VMs while still allowing efficient and secure access to download and sstate caches.

use pengutronix-hosted runner

---

classes-recipe/bundle.bbclass

To not confuse with the upcoming RAUC 'artifacts', remove all mentions of the word 'artifacts' used in other context.

bundle.bbclass: remove mentions of 'artifacts'

---

classes-recipe/bundle.bbclass

Rerun `do_bundle` task when `RAUC_CERT_FILE` or `RAUC_KEY_FILE` files have been changed on the disk.

bundle.bbclass: extend do_bundle[file-checksums]

---

.github/workflows/build.yml
.github/workflows/schedule-builds.yml

We currently only test the master branch on a regular schedule and not the different release branches (like e.g. scarthgap or styhead).
Also testing these other branches is complicated by the following detail in the GitHub action [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule):
> Scheduled workflows will only run on the default branch
This means we need some sort of workaround to run scheduled jobs on different branches. This commit adds a scheduled job on the master branch to trigger jobs on other branches via the `workflow_dispatch` event.
Build the master branch as well as all current release branches.
This PR is based on a very similar PR in meta-labgrid: …

.github/workflows/schedule-builds: Run scheduled jobs via workflow_dispatch

---

README.rst

The previous badge pointed to the `meta-rauc.yml` workflow file, which is no longer used in any branch.
Instead the workflow now resides in `build.yml` in all branches.
Daily scheduled builds are triggered from `schedule-builds.yml` via `workflow_dispatch` for all branches.
Display the status of the most recent `workflow_dispatch` build for all currently supported branches.
We should likely include the release name in the respective `build.yml` for each branch so it is shown in the badge.

README: update GitHub CI badges

---

classes-recipe/bundle.bbclass

If IMAGE_FSTYPES is empty, split() will return an empty array, resulting
in an `IndexError: list index out of range` error during parsing. The
`or ""` appears to be a previous attempt to handle this, but it is
ineffective, and not actually needed: OE-core's bitbake.conf contains a
default assignment for `IMAGE_FSTYPES`, so d.getVar() should always
return a (possibly empty) string.
We have come across this issue in combination with meta-ti, which
defines a multiconfig + additional machine for the Cortex-R5 core of TI
SoCs. This machine is only used to build bootloader and firmware recipes,
so IMAGE_FSTYPES is empty. As all recipes are parsed for all multiconfigs
unless skipped explicitly, just the existence of the core-bundle-minimal
recipe is enough to bring down the whole build in this …

bundle.bbclass: fix parsing with empty IMAGE_FSTYPES

---

classes-recipe/bundle.bbclass

If IMAGE_FSTYPES is empty, split() will return an empty array, resulting in an `IndexError: list index out of range` error during parsing. The `or ""` appears to be a previous attempt to handle this, but it is ineffective, and not actually needed: OE-core's bitbake.conf contains a default assignment for `IMAGE_FSTYPES`, so d.getVar() should always return a (possibly empty) string.
We have come across this issue in combination with meta-ti, which defines a multiconfig + additional machine for the Cortex-R5 core of TI SoCs. This machine is only used to build bootloader and firmware recipes, so IMAGE_FSTYPES is empty. As all recipes are parsed for all multiconfigs unless skipped explicitly, just the existence of the core-bundle-minimal recipe is enough to bring down the whole build in this …

[Scarthgap] bundle.bbclass: fix parsing with empty IMAGE_FSTYPES

---

classes-recipe/bundle.bbclass

This is useful only in combination with the upcoming support for artifacts, but shouldn't hurt the standard case for now.

bundle.bbclass: support manifest generation for artifacts

---

recipes-core/rauc/rauc-target.inc

All configuration was moved to the rauc-conf recipe in d51bab8f ("rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration") but these lines were accidentally duplicated. Since they have no meaning in the rauc recipe, remove them.

rauc-target: remove remnants of config handling

---

.github/workflows/build.yml

Since walnascar, the minimum required bitbake version will be 3.9.0:
> RuntimeError: Sorry, python 3.9.0 or later is required for this version of bitbake
This will allow continuing to run the GitHub actions on the GH-hosted runners.
Also, explicitly install 'chrpath', which does not seem to be part of the default installation anymore.

.github/workflows/build: run on ubuntu 22.04 for python > 3.8.x

---

classes-recipe/bundle.bbclass

The bundle section in the manifest was introduced with rauc v1.5. Versions prior to that fail to parse this section. As the section is optional for plain bundles it should be dropped from the manifest to ensure updates can be done even with an old rauc version on the target.

bundle.bbclass: make plain bundles compatible with older rauc versions

---

recipes-core/rauc/rauc.inc

With RAUC v1.14, RAUC optionally supports composefs artifact repositories. This adds the necessary option to enable it.
It is disabled by default since the composefs recipe resides in meta-oe.

rauc: add PACKAGECONFIG option for composefs

---

.github/workflows/schedule-builds.yml
README.rst

Support for the Yocto `walnascar` release has recently been added to `meta-rauc`.
Also run periodic builds for the release and display their status in the `README.rst`.

CI: run periodic builds for the walnascar branch

---

.github/workflows/schedule-builds.yml
README.rst
conf/layer.conf

The styhead release has gone out of support as of April 2025.
Time to remove support for it.

layer.conf: remove 'styhead' from LAYERSERIES_COMPAT

---

.github/workflows/build.yml

The `python3-distutils` package is no longer available in Debian trixie and the [`python3-setuptools`](https://packages.debian.org/trixie/python3-setuptools) package provides a compatibility layer for it.
In Debian bookworm the python3-setuptools package depends on python3-distutils, so it will be installed either way.
Build on trixie without this change: https://github.com/pengutronix-test/meta-rauc/actions/runs/16957285236
Build on trixie with this change: https://github.com/pengutronix-test/meta-rauc/actions/runs/16957342688

[kirkstone] CI: install python3-setuptools instead of -distutils
